name: Cargo Build & Test

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: Build & Test Console Static Text
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose --all-features
      - run: cargo test --verbose --all-features
